# Site settings
title: Szkolenie
description: Szkolenie java dla początkujących

remote_theme: g2forge/charcoal
author_name: NSq1
author_url: https://github.com/NSq1/
repository: NSq1/szkolenie
toc: true                             # Adds a table of contents to the left sidebar of the page